### ISSUE TITLE
Can you provide the file for creating mnist dataset?

### ISSUE THREAD

**Issue by EvaFlower** [utkarshojha/elastic-infogan#1]
Hi there,

Your work is interesting. I want to reproduce the paper results. Can you provide the following files?

./splits/70k.pt contains the original MNIST dataset.
./splits/50_data_imbalance.npy contains 50 (random) class-imbalance information.

Thanks and Regards,

**Comment by utkarshojha** [comment]
Hi, apologies for the delayed response. I have provided the links to the file, and updated the readme accordingly.
